### ISSUE TITLE
Suggested Improvements

### ISSUE THREAD

**Issue by lachieh** [FrontEndHappyHour/frontendhappyhour.github.io#118]
Hey Team,

I've got a couple of suggestions but I don't want to assume anything, so I'll ask before putting in the time.

* Prettier
* Stylelint
* Updated Eslint + new rules file
* Pre-commit Prettier + Eslint + Stylelint enforcement
* Updated tests + support for Node 10+
* Remove Node 4 + 6 Support

Are you open to PRs for these things?

**Comment by augbog** [comment]
We're always open to PRs :)

**Comment by lachieh** [comment]
Closed in #128
