### ISSUE TITLE
React is not uglified.

### ISSUE THREAD

**Issue by vramana** [FrontEndHappyHour/frontendhappyhour.github.io#59]
![image](https://cloud.githubusercontent.com/assets/3112509/22013612/eab0a7a6-dcbf-11e6-838f-8ca89ecf6207.png)

A few more things to consider:
1. Seperate react into vendor bundle that can be shared across all pages. 
2. Either switch to preact or inferno for better bundle size.

**Comment by ryanburgess** [comment]
All great suggestions!

**Comment by vramana** [comment]
Will you interested in switching to webpack whereever possible?

**Comment by ryanburgess** [comment]
Webpack is great. We could switch to using webpack but just haven't at this time.

I'm going to close this issue for now since the JS is now using the minified bundle.
